from typing import List, Tuple

class MegaNode:
    name: str
    handle: str
    size: int
    timestamp: int
    is_file: bool
    is_folder: bool

class MegaSession:
    @staticmethod
    async def login(email: str, password: str) -> "MegaSession": ...
    
    async def refresh(self) -> None: ...
    async def list(self, path: str) -> List[MegaNode]: ...
    async def quota(self) -> Tuple[int, int]: ...
    async def mkdir(self, path: str) -> None: ...
    async def rename(self, path: str, new_name: str) -> None: ...
    async def mv(self, source: str, dest: str) -> None: ...
    async def rm(self, path: str) -> None: ...
    async def export(self, path: str) -> str: ...
    async def upload(self, local_path: str, remote_path: str) -> str: ...
    async def download(self, remote_path: str, local_path: str) -> str: ...
    async def get_email(self) -> str: ...

class MegaRegistrationState:
    def serialize(self) -> str: ...
    @staticmethod
    def deserialize(s: str) -> "MegaRegistrationState": ...

class MegaPublicFile:
    name: str
    size: int
    handle: str

async def register(email: str, password: str, name: str) -> MegaRegistrationState: ...
async def verify_registration(state: MegaRegistrationState, signup_key: str) -> None: ...

async def get_public_file_info(url: str) -> MegaPublicFile: ...
async def download_public_file(url: str, local_path: str) -> str: ...
