from typing import List, Tuple

class MegaNode:
    name: str
    handle: str
    size: int
    timestamp: int
    is_file: bool
    is_folder: bool

class MegaSession:
    @staticmethod
    async def login(email: str, password: str, proxy: str | None = None) -> "MegaSession": ...
    @staticmethod
    async def load(path: str) -> "MegaSession | None": ...
    
    async def refresh(self) -> None: ...
    async def save(self, path: str) -> None: ...
    async def stat(self, path: str) -> MegaNode | None: ...
    async def list(self, path: str, recursive: bool = False) -> List[MegaNode]: ...
    async def quota(self) -> Tuple[int, int]: ...
    async def mkdir(self, path: str) -> None: ...
    async def rename(self, path: str, new_name: str) -> None: ...
    async def mv(self, source: str, dest: str) -> None: ...
    async def rm(self, path: str) -> None: ...
    async def export(self, path: str) -> str: ...
    async def upload(self, local_path: str, remote_path: str) -> str: ...
    async def download(self, remote_path: str, local_path: str) -> str: ...
    async def get_email(self) -> str: ...
    async def get_name(self) -> str | None: ...
    async def get_handle(self) -> str: ...
    async def set_workers(self, workers: int) -> None: ...
    async def set_resume(self, enabled: bool) -> None: ...
    async def enable_previews(self, enabled: bool) -> None: ...
    async def share_folder(self, path: str, email: str, access_level: int) -> None: ...
    async def list_contacts(self) -> List[MegaNode]: ...

class MegaRegistrationState:
    def serialize(self) -> str: ...
    @staticmethod
    def deserialize(s: str) -> "MegaRegistrationState": ...

class MegaPublicFile:
    name: str
    size: int
    handle: str

class MegaPublicFolder:
    async def list(self, path: str) -> List[MegaNode]: ...
    async def download(self, remote_path: str, local_path: str) -> str: ...

async def register(email: str, password: str, name: str) -> MegaRegistrationState: ...
async def verify_registration(state: MegaRegistrationState, signup_key: str) -> None: ...

async def get_public_file_info(url: str) -> MegaPublicFile: ...
async def download_public_file(url: str, local_path: str) -> str: ...
async def open_folder(url: str) -> MegaPublicFolder: ...
